library(ggplot2)
NEI<-readRDS("summarySCC_PM25.rds")
SCC<-readRDS("Source_Classification_Code.rds")
balt<-subset(NEI,fips=="24510")
balttot<-tapply(balt$Emissions,balt$year,sum)
balt.sources <- aggregate(balt[c("Emissions")], list(type = balt$type, year = balt$year), sum)
qplot(year, Emissions, data=balt.sources, color= type, geom="line")+ggtitle(" Total Baltimore"~PM[2.5]~"Emissions (tons) by Source")+xlab("Years")+ylab("Emissions")
dev.copy(png, file="plot3.png", height=480, width=480)
dev.off()